#include "ScenarioConverter.h"
#include <QDateTime>
#include <QMath.h>
#include <QDebug>

#ifndef M_PI
#define M_PI 3.14159265358979323846
#endif

// 分隔符常量 (与 RA_BASIC ra_order.h 一致)
static const char* SEP_L1 = "|";   // 指令头与数据分隔
static const char* SEP_L2 = "`";   // 速度与航线点分隔
static const char* SEP_L3 = "~";   // 航线点之间分隔
static const char* SEP_L4 = "$";   // 经度/纬度/高度分隔

static const double MS_TO_KTS = 1.94384;
static const double DEG_TO_RAD = M_PI / 180.0;
static const double METERS_PER_DEG = 111320.0;

// ============================================================================
// 校验
// ============================================================================

bool ScenarioConverter::validateScenario(const QJsonObject& json, QString& errorMsg)
{
    if (json.isEmpty()) {
        errorMsg = "scenario object is empty";
        return false;
    }
    if (!json.contains("vecTeam")) {
        errorMsg = "missing required field: vecTeam";
        return false;
    }
    const QJsonArray teams = json["vecTeam"].toArray();
    if (teams.isEmpty()) {
        errorMsg = "vecTeam is empty, at least one team required";
        return false;
    }
    for (int i = 0; i < teams.size(); ++i) {
        QJsonObject team = teams[i].toObject();
        QJsonObject manner = team["tObjManner"].toObject();
        if (manner.isEmpty()) {
            errorMsg = QString("team[%1] missing tObjManner").arg(i);
            return false;
        }
        QJsonObject status = manner["iObjStatus"].toObject();
        if (status.isEmpty()) {
            errorMsg = QString("team[%1].tObjManner missing iObjStatus").arg(i);
            return false;
        }
        QJsonObject pos = status["iPos"].toObject();
        if (pos.isEmpty()) {
            errorMsg = QString("team[%1].tObjManner.iObjStatus missing iPos").arg(i);
            return false;
        }
    }
    return true;
}

// ============================================================================
// 主转换入口
// ============================================================================

QString ScenarioConverter::convertToAfsimTxt(const QJsonObject& json)
{
    QString out;
    QTextStream ts(&out);

    // ---- 头部注释 ----
    QString name  = json["strScenarioName"].toString("unnamed");
    QString author = json["strAuthor"].toString("unknown");
    QString desc  = json["strDescription"].toString("");

    ts << "# Generated by RASimBackend init_scenario\n";
    ts << "# 想定名称: " << name << "\n";
    ts << "# 制作者: " << author << "\n";
    if (!desc.isEmpty())
        ts << "# 描述: " << desc << "\n";
    ts << "\n";

    ts << "frame_time 0.016 seconds\n\n";

    // ---- 计算仿真时长 ----
    QString strStart = json["strStartTime"].toString();
    QString strEnd   = json["strEndTime"].toString();
    double endSec = calcEndTimeSec(strStart, strEnd);
    if (endSec <= 0) endSec = 1800.0;

    // ---- 收集所有用到的平台类型，生成 platform_type 块 ----
    QSet<int> usedPlatTypes;
    QJsonArray teams = json["vecTeam"].toArray();
    for (const QJsonValue& tv : teams) {
        QJsonObject team = tv.toObject();
        QJsonObject manner = team["tObjManner"].toObject();
        QJsonObject baseInfo = manner["iBaseInfo"].toObject();
        int typeId = baseInfo["nTypeID"].toInt(1);
        usedPlatTypes.insert(typeId);
        // 编队成员也检查
        QJsonArray members = team["vecTeamInfo"].toArray();
        for (const QJsonValue& mv : members) {
            QJsonObject member = mv.toObject();
            QJsonObject mBase = member["iBaseInfo"].toObject();
            int mTypeId = mBase["nTypeID"].toInt(typeId);
            usedPlatTypes.insert(mTypeId);
        }
    }

    ts << "# ---- 平台类型定义 ----\n\n";
    for (int typeId : usedPlatTypes) {
        QString cat = platTypeToCategory(typeId);
        QString mover = platTypeToMover(typeId, false);
        QString icon  = platTypeToIcon(typeId);
        ts << "platform_type RA_" << cat.toUpper() << " WSF_PLATFORM\n";
        ts << "   icon " << icon << "\n";
        ts << "   category " << cat << "\n";
        if (!mover.isEmpty()) {
            ts << "   mover " << mover << "\n";
            ts << "      at_end_of_path extrapolate\n";
            ts << "   end_mover\n";
        }
        ts << "end_platform_type\n\n";
    }

    // ---- 生成平台实例 ----
    ts << "# ---- 平台实例 ----\n\n";

    // 解析延时指令，构建平台ID->航线数据映射
    QMap<QString, ParsedRouteOrder> routeOrders = parsePendingOrders(json);

    for (const QJsonValue& tv : teams) {
        QJsonObject team = tv.toObject();
        QJsonObject manner = team["tObjManner"].toObject();
        QJsonObject baseInfo = manner["iBaseInfo"].toObject();
        QJsonObject status   = manner["iObjStatus"].toObject();
        QJsonObject pos      = status["iPos"].toObject();
        QJsonObject hpr      = status["iHpr"].toObject();

        QString teamId = manner["str_id"].toString(team["strTeamID"].toString("unknown"));
        int factionId  = baseInfo["nFactionID"].toInt(1);
        int typeId     = baseInfo["nTypeID"].toInt(1);
        bool isStatic  = manner["bStatic"].toBool(false);

        QString side = factionToSide(factionId);
        QString cat  = platTypeToCategory(typeId);
        QString typeName = QString("RA_%1").arg(cat.toUpper());

        double lon = pos["x"].toDouble(0.0);
        double lat = pos["y"].toDouble(0.0);
        double alt = pos["z"].toDouble(0.0);
        double heading = hpr["x"].toDouble(0.0);
        double speed   = status["dHSpd"].toDouble(0.0);

        // 载荷
        QJsonObject payloads = team["map_load"].toObject();

        ts << genPlatform(teamId, typeName, side, cat,
                          lon, lat, alt, heading, speed,
                          isStatic, endSec, payloads, routeOrders);

        // ---- 编队成员 ----
        QJsonArray members = team["vecTeamInfo"].toArray();
        for (const QJsonValue& mv : members) {
            QJsonObject member = mv.toObject();
            QJsonObject mBase = member["iBaseInfo"].toObject();
            QJsonObject relPos = member["iRelativePos"].toObject();

            QString memberId = member["strObjID"].toString();
            int mFactionId = mBase["nFactionID"].toInt(factionId);
            int mTypeId    = mBase["nTypeID"].toInt(typeId);

            QString mSide = factionToSide(mFactionId);
            QString mCat  = platTypeToCategory(mTypeId);
            QString mTypeName = QString("RA_%1").arg(mCat.toUpper());

            double relDis = relPos["dRelativeDis"].toDouble(0.0);
            double relHdg = relPos["dRelativeHdg"].toDouble(0.0);
            double relAlt = relPos["dRelativeAlt"].toDouble(0.0);

            double mLon, mLat, mAlt;
            calcMemberPosition(lon, lat, alt, heading, relDis, relHdg, relAlt,
                               mLon, mLat, mAlt);

            QJsonObject mPayloads = member["map_load"].toObject();

            ts << genPlatform(memberId, mTypeName, mSide, mCat,
                              mLon, mLat, mAlt, heading, speed,
                              isStatic, endSec, mPayloads, routeOrders);
        }
    }

    // ---- 区域 ----
    QJsonArray areas = json["vecArea"].toArray();
    if (!areas.isEmpty()) {
        ts << "# ---- 区域 ----\n\n";
        for (int i = 0; i < areas.size(); ++i) {
            ts << genZone(QString("area_%1").arg(i), areas[i].toObject());
        }
    }

    // ---- 仿真时长 ----
    ts << "# ---- 仿真时长 ----\n";
    ts << "end_time " << static_cast<int>(endSec) << " sec\n";

    ts.flush();
    return out;
}

// ============================================================================
// 映射函数
// ============================================================================

QString ScenarioConverter::factionToSide(int factionId)
{
    switch (factionId) {
    case 1:  return "red";
    case 2:  return "blue";
    case 3:  return "green";
    case 4:  return "yellow";
    case 5:  return "green";
    default: return "red";
    }
}

QString ScenarioConverter::platTypeToCategory(int typeId)
{
    switch (typeId) {
    case 1:     return "fighter";     // TYPE_AIRCRAFT
    case 2:     return "ship";        // TYPE_WARSHIP
    case 4:     return "submarine";   // TYPE_SUBMARINE
    case 8:     return "truck";       // TYPE_VEHICLE
    case 16:    return "satellite";   // TYPE_SATELLITE
    case 32:    return "person";      // TYPE_PERSON
    case 64:    return "mine";        // TYPE_MINE
    case 32768: return "building";    // TYPE_BUILDING
    case 65536: return "landmark";    // TYPE_LANDMARK
    default:    return "platform";
    }
}

QString ScenarioConverter::platTypeToMover(int typeId, bool isStatic)
{
    if (isStatic) return QString();
    switch (typeId) {
    case 1:     return "WSF_AIR_MOVER";
    case 2:     return "WSF_SURFACE_MOVER";
    case 4:     return "WSF_SURFACE_MOVER";
    case 8:     return "WSF_SURFACE_MOVER";
    case 16:    return "WSF_SPACE_MOVER";
    default:    return QString();
    }
}

QString ScenarioConverter::platTypeToIcon(int typeId)
{
    switch (typeId) {
    case 1:     return "f15c";
    case 2:     return "ship";
    case 4:     return "submarine";
    case 8:     return "truck";
    case 16:    return "satellite";
    case 32:    return "person";
    case 64:    return "mine";
    case 32768: return "building";
    case 65536: return "landmark";
    default:    return "platform";
    }
}

QString ScenarioConverter::partTypeToAfsim(int typeId)
{
    // TYPE_RADAR = 1<<20 = 1048576
    if (typeId & (1 << 20)) return "sensor";
    // TYPE_SONAR = 1<<21 = 2097152
    if (typeId & (1 << 21)) return "sensor";
    // TYPE_MISSILE = 1<<18 = 262144
    if (typeId & (1 << 18)) return "weapon";
    // TYPE_JAMMER = 1<<22 = 4194304
    if (typeId & (1 << 22)) return "sensor";  // EW sensor placeholder
    // TYPE_PSE = 1<<26 = 67108864
    if (typeId & (1 << 26)) return "sensor";
    return QString();
}

// ============================================================================
// 格式化辅助
// ============================================================================

QString ScenarioConverter::formatPosition(double lon, double lat, double altM)
{
    // AFSIM 支持: position 30.37n 120.74e altitude 5000 m
    QString latDir = (lat >= 0) ? "n" : "s";
    QString lonDir = (lon >= 0) ? "e" : "w";
    return QString("position %1%2 %3%4 altitude %5 m")
        .arg(qFabs(lat), 0, 'f', 6)
        .arg(latDir)
        .arg(qFabs(lon), 0, 'f', 6)
        .arg(lonDir)
        .arg(altM, 0, 'f', 1);
}

QString ScenarioConverter::formatSpeed(double speedMs)
{
    double kts = speedMs * MS_TO_KTS;
    return QString::number(qFabs(kts), 'f', 1) + " kts";
}

bool ScenarioConverter::isCoincident(double lon1, double lat1, double alt1,
                                     double lon2, double lat2, double alt2)
{
    static const double POS_EPS = 1e-5;  // ~1.1m
    static const double ALT_EPS = 1.0;   // 1m
    return qFabs(lon1 - lon2) < POS_EPS &&
           qFabs(lat1 - lat2) < POS_EPS &&
           qFabs(alt1 - alt2) < ALT_EPS;
}

// ============================================================================
// 时间计算
// ============================================================================

double ScenarioConverter::calcEndTimeSec(const QString& start, const QString& end)
{
    if (start.isEmpty() || end.isEmpty()) return 0.0;
    QDateTime dtStart = QDateTime::fromString(start, "yyyy-MM-dd hh:mm:ss");
    QDateTime dtEnd   = QDateTime::fromString(end,   "yyyy-MM-dd hh:mm:ss");
    if (!dtStart.isValid() || !dtEnd.isValid()) return 0.0;
    return dtStart.secsTo(dtEnd);
}

// ============================================================================
// 子块生成
// ============================================================================

QString ScenarioConverter::genPlatformType(const QString& typeName, int typeId, bool isStatic)
{
    QString cat = platTypeToCategory(typeId);
    QString mover = platTypeToMover(typeId, isStatic);
    QString icon  = platTypeToIcon(typeId);

    QString out;
    QTextStream ts(&out);
    ts << "platform_type " << typeName << " WSF_PLATFORM\n";
    ts << "   icon " << icon << "\n";
    ts << "   category " << cat << "\n";
    if (!mover.isEmpty()) {
        ts << "   mover " << mover << "\n";
        ts << "      at_end_of_path extrapolate\n";
        ts << "   end_mover\n";
    }
    ts << "end_platform_type\n\n";
    ts.flush();
    return out;
}

QString ScenarioConverter::genPlatform(const QString& instanceName,
                                       const QString& typeName,
                                       const QString& side,
                                       const QString& category,
                                       double lon, double lat, double altM,
                                       double heading, double speedMs,
                                       bool isStatic,
                                       double endSec,
                                       const QJsonObject& payloads,
                                       const QMap<QString, ParsedRouteOrder>& routeOrders)
{
    QString out;
    QTextStream ts(&out);

    ts << "platform " << instanceName << " " << typeName << "\n";
    ts << "   side " << side << "\n";
    ts << "   category " << category << "\n";
    ts << "   " << formatPosition(lon, lat, altM) << "\n";
    ts << "   heading " << QString::number(heading, 'f', 1) << " deg\n";

    // 航路生成：优先使用 vecPendingOrder 中的航线，否则回退到简单两点航路
    auto orderIt = routeOrders.find(instanceName);
    if (!isStatic && orderIt != routeOrders.end() && !orderIt->waypoints.isEmpty()) {
        // 使用 vecPendingOrder 中的多点航线，跳过连续重复的航路点
        // AFSIM 会将平台初始化到 route 的第一个航路点，所以必须以平台 position 为锚点
        const ParsedRouteOrder& order = orderIt.value();
        QVector<RouteWaypoint> filtered;
        RouteWaypoint startPos{lon, lat, altM};
        filtered.append(startPos);
        for (const RouteWaypoint& wp : order.waypoints) {
            if (isCoincident(wp.lon, wp.lat, wp.alt,
                             filtered.last().lon, filtered.last().lat, filtered.last().alt))
                continue;
            filtered.append(wp);
        }
        if (!filtered.isEmpty()) {
            ts << "   route\n";
            for (const RouteWaypoint& wp : filtered) {
                ts << "      " << formatPosition(wp.lon, wp.lat, wp.alt)
                   << " speed " << formatSpeed(order.speedMs) << "\n";
            }
            ts << "   end_route\n";
        }
    } else if (!isStatic && speedMs > 0.1) {
        // 回退：沿航向投影一个点作为航路终点
        double hdgRad = heading * DEG_TO_RAD;
        double distM = speedMs * endSec;
        // 限制最大距离为 500km 以保持合理
        if (distM > 500000.0) distM = 500000.0;
        double deltaLat = -(distM * cos(hdgRad)) / METERS_PER_DEG;
        double deltaLon = (distM * sin(hdgRad)) / (METERS_PER_DEG * cos(lat * DEG_TO_RAD));
        double endLon = lon + deltaLon;
        double endLat = lat + deltaLat;

        ts << "   route\n";
        ts << "      " << formatPosition(lon, lat, altM)
           << " speed " << formatSpeed(speedMs) << "\n";
        ts << "      " << formatPosition(endLon, endLat, altM)
           << " speed " << formatSpeed(speedMs) << "\n";
        ts << "   end_route\n";
    }

    // 载荷
    QString payloadBlock = genPayloads(payloads);
    if (!payloadBlock.isEmpty()) {
        ts << payloadBlock;
    }

    ts << "end_platform\n\n";
    ts.flush();
    return out;
}

QString ScenarioConverter::genPayloads(const QJsonObject& payloads)
{
    if (payloads.isEmpty()) return QString();

    QString out;
    QTextStream ts(&out);

    for (auto it = payloads.begin(); it != payloads.end(); ++it) {
        QJsonObject part = it.value().toObject();
        QJsonObject baseInfo = part["iBaseInfo"].toObject();
        int typeId = baseInfo["nTypeID"].toInt(0);
        QString partId = part["strPartID"].toString(it.key());

        QString afsimType = partTypeToAfsim(typeId);
        if (afsimType == "sensor") {
            ts << "   sensor " << partId << " WSF_SENSOR\n";
            ts << "      on\n";
            ts << "   end_sensor\n";
        } else if (afsimType == "weapon") {
            ts << "   weapon " << partId << " WSF_EXPLICIT_WEAPON\n";
            ts << "      quantity 4\n";
            ts << "   end_weapon\n";
        }
        // 其他类型 v1 暂不处理

        // 递归处理子载荷
        QJsonObject subParts = part["map_load_part"].toObject();
        if (!subParts.isEmpty()) {
            ts << genPayloads(subParts);
        }
    }

    ts.flush();
    return out;
}

QString ScenarioConverter::genZone(const QString& name, const QJsonObject& area)
{
    QString out;
    QTextStream ts(&out);

    int areaType = area["nAreaType"].toInt(0);
    QString message = area["sMessage"].toString(name);
    double upH   = area["dUpHeight"].toDouble(10000.0);
    double downH = area["dDownHeight"].toDouble(0.0);
    QJsonArray points = area["vecPoint"].toArray();

    if (points.isEmpty()) return QString();

    ts << "# 区域: " << message << "\n";

    if (areaType == 1) {
        // 圆形区域 — AFSIM 用 cylindrical zone
        if (points.size() >= 1) {
            QJsonObject center = points[0].toObject();
            double cLon = center["x"].toDouble(0.0);
            double cLat = center["y"].toDouble(0.0);
            double radius = 10000.0; // 默认 10km
            if (points.size() >= 2) {
                QJsonObject edge = points[1].toObject();
                double eLon = edge["x"].toDouble(0.0);
                double eLat = edge["y"].toDouble(0.0);
                double dLat = (eLat - cLat) * METERS_PER_DEG;
                double dLon = (eLon - cLon) * METERS_PER_DEG * cos(cLat * DEG_TO_RAD);
                radius = sqrt(dLat * dLat + dLon * dLon);
            }
            ts << "zone " << name << "\n";
            ts << "   cylindrical lat_lon\n";
            ts << "      center " << QString::number(qFabs(cLat), 'f', 6)
               << (cLat >= 0 ? "n " : "s ")
               << QString::number(qFabs(cLon), 'f', 6)
               << (cLon >= 0 ? "e " : "w ") << "\n";
            ts << "      radius " << QString::number(radius, 'f', 1) << " m\n";
            ts << "   minimum_altitude " << QString::number(downH, 'f', 1) << " m\n";
            ts << "   maximum_altitude " << QString::number(upH, 'f', 1) << " m\n";
            ts << "end_zone\n\n";
        }
    } else {
        // 多边形区域
        ts << "zone " << name << "\n";
        ts << "   polygonal lat_lon\n";
        for (const QJsonValue& pv : points) {
            QJsonObject pt = pv.toObject();
            double pLon = pt["x"].toDouble(0.0);
            double pLat = pt["y"].toDouble(0.0);
            ts << "      point "
               << QString::number(qFabs(pLat), 'f', 6)
               << (pLat >= 0 ? "n " : "s ")
               << QString::number(qFabs(pLon), 'f', 6)
               << (pLon >= 0 ? "e" : "w") << "\n";
        }
        ts << "   minimum_altitude " << QString::number(downH, 'f', 1) << " m\n";
        ts << "   maximum_altitude " << QString::number(upH, 'f', 1) << " m\n";
        ts << "end_zone\n\n";
    }

    ts.flush();
    return out;
}

// ============================================================================
// 编队成员绝对位置计算
// ============================================================================

void ScenarioConverter::calcMemberPosition(double leaderLon, double leaderLat, double leaderAlt,
                                           double leaderHdg,
                                           double relDis, double relHdg, double relAlt,
                                           double& outLon, double& outLat, double& outAlt)
{
    double totalHdgRad = (leaderHdg + relHdg) * DEG_TO_RAD;
    double deltaLat = -(relDis * cos(totalHdgRad)) / METERS_PER_DEG;
    double deltaLon = (relDis * sin(totalHdgRad)) / (METERS_PER_DEG * cos(leaderLat * DEG_TO_RAD));

    outLat = leaderLat + deltaLat;
    outLon = leaderLon + deltaLon;
    outAlt = leaderAlt + relAlt;
}

// ============================================================================
// 延时指令解析
// ============================================================================

QMap<QString, ScenarioConverter::ParsedRouteOrder>
ScenarioConverter::parsePendingOrders(const QJsonObject& json)
{
    QMap<QString, ParsedRouteOrder> result;

    QJsonArray orders = json["vecPendingOrder"].toArray();
    if (orders.isEmpty()) return result;

    for (const QJsonValue& ov : orders) {
        QString orderStr = ov.toString();
        if (orderStr.isEmpty()) continue;

        // 指令头 | 航线数据
        QStringList level1 = orderStr.split(SEP_L1);
        if (level1.size() < 2) continue;

        // 解析指令头: 定速航线,平台ID,...
        QStringList header = level1[0].split(",");
        if (header.size() < 2) continue;

        QString orderType = header[0].trimmed();
        QString platformId = header[1].trimmed();

        // 目前只处理 "定速航线"
        if (orderType != QStringLiteral("定速航线")) continue;

        // 航线数据: 速度`航线点1~航线点2~...
        QStringList level2 = level1[1].split(SEP_L2);
        if (level2.size() < 2) continue;

        double speedMs = level2[0].trimmed().toDouble();
        if (speedMs <= 0.0) continue;

        QString waypointsStr = level2[1];
        QStringList pointStrs = waypointsStr.split(SEP_L3);

        ParsedRouteOrder order;
        order.speedMs = speedMs;

        for (const QString& ptStr : pointStrs) {
            QString trimmed = ptStr.trimmed();
            if (trimmed.isEmpty()) continue;
            QStringList coords = trimmed.split(SEP_L4);
            if (coords.size() < 3) continue;

            RouteWaypoint wp;
            wp.lon = coords[0].toDouble();
            wp.lat = coords[1].toDouble();
            wp.alt = coords[2].toDouble();
            order.waypoints.append(wp);
        }

        if (order.waypoints.size() >= 2) {
            result[platformId] = order;
        }
    }

    return result;
}
